services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "portfolio_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "54326:5432"
    volumes:
      - ./portfolio_db/postgres/data:/var/lib/postgresql/data
    networks:
      - postgres_network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - postgres_network

networks:
  postgres_network:
    driver: bridge